### ISSUE TITLE
v1.0.0 fails with "Error: spawn UNKNOWN" on windows, previously did work with v0.2.3

### ISSUE THREAD

**Issue by jeffbski** [karma-runner/karma-phantomjs-launcher#105]
I just upgraded karma-phantomjs-launcher and from phantomjs to phantomjs-prebuilt and now I get the following error when running on windows. It works fine on my Mac, so only windows is broken.

The previous version 0.2.3 worked fine on windows.

```
25 02 2016 18:26:23.808:ERROR [launcher]: { [Error: spawn UNKNOWN] code: 'UNKNOW
N', errno: 'UNKNOWN', syscall: 'spawn' }
Error: spawn UNKNOWN
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at Object._execCommand (c:\MinGW\working\reactjs-101\node_modules\karma\lib\launchers\process.js:63:21)
    at Object._start (c:\MinGW\working\reactjs-101\node_modules\karma-phantomjs-launcher\index.js:76:10)
    at Object.<anonymous> (c:\MinGW\working\reactjs-101\node_modules\karma\lib\launchers\process.js:14:10)
    at emitOne (events.js:82:20)
    at Object.emit (events.js:169:7)
    at Object.start (c:\MinGW\working\reactjs-101\node_modules\karma\lib\launchers\base.js:42:10)
    at c:\MinGW\working\reactjs-101\node_modules\karma\lib\launcher.js:94:17
    at next (c:\MinGW\working\reactjs-101\node_modules\karma\node_modules\batch\index.js:118:7)
    at Batch.end (c:\MinGW\working\reactjs-101\node_modules\karma\node_modules\batch\index.js:154:5)
    at launch (c:\MinGW\working\reactjs-101\node_modules\karma\lib\launcher.js:111:11)
    at invoke (c:\MinGW\working\reactjs-101\node_modules\karma\node_modules\di\lib\injector.js:75:15)
    at Server.<anonymous> (c:\MinGW\working\reactjs-101\node_modules\karma\lib\server.js:171:24)
    at Server.g (events.js:260:16)
```

**Comment by dignifiedquire** [comment]
Thanks for the report. Does running phantomjs prebuilt on its own work?

**Comment by jeffbski** [comment]
It looks like it is a phantomjs-prebuilt problem since the tests cause the same error, so I have logged the issue https://github.com/Medium/phantomjs/issues/478
