### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by cheskos** [karma-runner/karma-phantomjs-launcher#133]
Hello. Got this when tried to install:
```
$ npm install -g karma-phantomjs-launcher
npm WARN peerDependencies The peer dependency karma@>=0.9 included from karma-phantomjs-launcher will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
/
> phantomjs-prebuilt@2.1.8 install C:\Users\Lenovo\AppData\Roaming\npm\node_modules\karma-phantomjs-launcher\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\Lenovo\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\Users\Lenovo\AppData\Roaming\npm\node_modules\karma-phantomjs-launcher\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\Lenovo\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1469725064693\phantomjs-2.1.1-windows -> C:\Users\Lenovo\AppData\Roaming\npm\node_modules\karma-phantomjs-launcher\node_modules\phantomjs-prebuilt\lib\phantom
Phantom installation failed { [Error: EPERM, unlink 'C:\Users\Lenovo\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1469725064693\phantomjs-2.1.1-windows\bin\phantomjs.exe']
  errno: -4048,
  code: 'EPERM',
  path: 'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\phantomjs\\phantomjs-2.1.1-windows.zip-extract-1469725064693\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe' } Error: EPERM, unlink 'C:\Users\Lenovo\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1469725064693\phantomjs-2.1.1-windows\bin\phantomjs.exe'
    at Error (native)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma-phantomjs-launcher"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.8 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.8 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WalabiProject\Front\debito-cordoba-app\cordova-app\npm-debug.log
```

Lines from log:
```
10324 verbose unlock done using C:\Users\Lenovo\AppData\Roaming\npm-cache\_locks\lodash-88f5eafaa0b82ebd.lock for C:\Users\Lenovo\AppData\Roaming\npm\node_modules\karma-phantomjs-launcher\node_modules\lodash
10325 info phantomjs-prebuilt@2.1.8 Failed to exec install script
10326 verbose unlock done using C:\Users\Lenovo\AppData\Roaming\npm-cache\_locks\phantomjs-prebuilt-4e7b102d1270ce1e.lock for C:\Users\Lenovo\AppData\Roaming\npm\node_modules\karma-phantomjs-launcher\node_modules\phantomjs-prebuilt
10327 verbose about to build C:\Users\Lenovo\AppData\Roaming\npm\node_modules\karma-phantomjs-launcher
10328 verbose unlock done using C:\Users\Lenovo\AppData\Roaming\npm-cache\_locks\karma-phantomjs-launcher-4c1a5dd62b430cf4.lock for C:\Users\Lenovo\AppData\Roaming\npm\node_modules\karma-phantomjs-launcher
10329 verbose stack Error: phantomjs-prebuilt@2.1.8 install: `node install.js`
10329 verbose stack Exit status 1
10329 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10329 verbose stack     at EventEmitter.emit (events.js:110:17)
10329 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10329 verbose stack     at ChildProcess.emit (events.js:110:17)
10329 verbose stack     at maybeClose (child_process.js:1015:16)
10329 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10330 verbose pkgid phantomjs-prebuilt@2.1.8
10331 verbose cwd C:\WalabiProject\Front\debito-cordoba-app\cordova-app
10332 error Windows_NT 6.3.9600
10333 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma-phantomjs-launcher"
10334 error node v0.12.2
10335 error npm  v2.7.4
10336 error code ELIFECYCLE
10337 error phantomjs-prebuilt@2.1.8 install: `node install.js`
10337 error Exit status 1
10338 error Failed at the phantomjs-prebuilt@2.1.8 install script 'node install.js'.
```

**Comment by dignifiedquire** [comment]
That's an issue with npm & phantomjs-prebuilt, not with this module I'm afraid.

**Comment by cheskos** [comment]
Thank you
