### ISSUE TITLE
Error: Cannot find module 'boom'

### ISSUE THREAD

**Issue by alexander-elgin** [karma-runner/karma-phantomjs-launcher#149]
I use karma-phantomjs-launcher to run unit tests on a CI (Shippable) server. In the `package.json` devDependencies I use `"karma-phantomjs-launcher": "^1.0.0"`. Since Monday (Dec 12th 2016) `npm install` fails with the following error

```
> phantomjs-prebuilt@2.1.14 install /home/shippable/workspace/src/github.com/rgi-assessment-tool/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt
> node install.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/shippable/workspace/src/github.com/rgi-assessment-tool/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
No modifications in the `package.json` was done since the last successful build. If I remove karma-phantomjs-launcher from the dependency list `npm install` works fine (but obviously the unit tests fail).

**Comment by kostkobv** [comment]
@alexander-elgin Thanks for your message first of all!

Seems like the problem is with installing the `phantomjs-prebuilt`. Still I need some additional information to check why that problem might take place:
- Can you please provide what version of Node.js is used on your CI?  
- Can you please provide the whole log for `npm install`?
- It would also be nice to look at your `package.json`

**Comment by alexander-elgin** [comment]
@kostkobv Thank you for the prompt response. I use "node":"0.10.48","npm":"2.15.1". Here is the [package.json.txt](https://github.com/karma-runner/karma-phantomjs-launcher/files/651386/package.json.txt) file. You can find the full log on https://app.shippable.com/runs/584e76179559830f0008f0e3/1/console

**Comment by alexander-elgin** [comment]
Hello @kostkobv, is there anything else I can do to help with fixing the issue?

**Comment by elizfunk** [comment]
When updating to version 1.0.2, I had a similar problem and error message:

`Error: Cannot find module 'boom'`

**Comment by elizfunk** [comment]
Downgrading to version 1.0.1 solved my problem.

**Comment by onlyurei** [comment]
+1
