### ISSUE TITLE
Spawn ENOTDIR after updating to High Sierra

### ISSUE THREAD

**Issue by rylek90** [karma-runner/karma-phantomjs-launcher#209]
However, I'm not sure if it's related with system update but it is the only change to already existing setup. Other Karma launchers work fine
NPM and Node 8.4.0
```
20 11 2017 09:32:40.073:ERROR [launcher]: { Error: spawn ENOTDIR
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.ProcessLauncher._execCommand (/src/node_modules/karma/lib/launchers/process.js:63:21)
    at Object.PhantomJSBrowser._start (/src/node_modules/karma-phantomjs-launcher/index.js:80:10)
    at Object.<anonymous> (/src/node_modules/karma/lib/launchers/process.js:14:10)
    at emitOne (events.js:120:20)
    at Object.emit (events.js:210:7)
    at Object.BaseLauncher.start (/src/node_modules/karma/lib/launchers/base.js:42:10)
    at /src/node_modules/karma/lib/launcher.js:94:17
    at next (/src/node_modules/batch/index.js:118:7)
    at Batch.end (/src/node_modules/batch/index.js:154:5)
    at Launcher.launch (/src/node_modules/karma/lib/launcher.js:111:11)
    at Injector.invoke (/src/node_modules/di/lib/injector.js:75:15)
    at Server.<anonymous> (/src/node_modules/karma/lib/server.js:171:24)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1349:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ENOTDIR', errno: 'ENOTDIR', syscall: 'spawn' }
```

**Comment by ghost** [comment]
I can confirm that I was receiving the same error after the update.  I was able to fix the issue by installing phantomjs globally because it seems like the binary was no longer available to the launcher.  I ran `npm install -g phantomjs` and was able to run my tests without issue afterwards.

**Comment by dignifiedquire** [comment]
I ran into the same issue today, it seems the only way to fix is to reinstall the dependencies. I suspect high sierra requires different binaries which will then be downloaded.

**Comment by wyssa14** [comment]
Same here. Reinstalling the dependencies worked for me.

**Comment by prosdev** [comment]
@rylek90 Referencing someone's response from [here](https://github.com/karma-runner/karma/issues/479). `npm install -g phantomjs` followed by `npm rebuild` worked for me. Not a karma runner issue, I believe. Hope this also helps someone!

**Comment by netdesignr** [comment]
Had the same issue. Thank you very much, guys!

**Comment by nithintkv** [comment]
Do we know the root cause of this issue?

**Comment by Ammet** [comment]
`npm install -g phantomjs` solved the issue. thanks guys!

**Comment by reganoneill** [comment]
worked for me too. thanks!

**Comment by michange** [comment]
npm rebuild worked for me

**Comment by sujithsreekumar** [comment]
I just deleted the node_modules folder and rebuilt my app.. All set!

**Comment by axelcaballero** [comment]
It worked for me, thanks

**Comment by HelloMihai** [comment]
`npm install -g phantomjs` fixed it for me.  Thank you
